// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once
#include "NativeGameplayTags.h"

namespace UE_GAS_StudyGameplayTags
{
	UE_GAS_STUDY_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Melee);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AirAttack);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_1);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_2);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_3);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_4);


	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);


	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	UE_GAS_STUDY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
}
